server:
  port: 8081
  tomcat:
    accept-count: 1000
    max-threads: 500
    min-spare-threads: 100


mybatis:
  mapperLocations: classpath:mapping/*.xml

spring:
  datasource:
    name: miaosha
    url: jdbc:mysql://127.0.0.1:3306/miaosha?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false