server:
  port: 8081
  tomcat:
    accept-count: 1000
    max-threads: 500
    min-spare-threads: 100
    accesslog:
      enabled: true
      directory: /logs
      pattern: '%h %l %u %t "%r" %s %b %D'


mybatis:
  mapperLocations: classpath:mapping/*.xml

spring:
  datasource:
    name: miaosha
    url: jdbc:mysql://172.17.0.2:3306/miaosha?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    host: 172.17.0.3
    port: 6379
    database: 10
    #password:
    jedis:
      pool:
        max-active: 50
        min-idle: 20

mq:
  nameserver:
    addr: 121.36.50.232:9876
  topicname: stock